In [15]:
import numpy as np

with open('test', 'r') as test:
    test = test.readlines()
print(test)

split = []
coord_size = []
for i in test:
    split_i = i.split()
    start_coord = split_i[2]
    size = split_i[3]
    start_coord_ = start_coord[:-1]
    start_coord_split = list(map(int, start_coord_.split(',')))
    size_split = list(map(int, size.split('x')))
    combined = (start_coord_split, size_split)
    split.append(split_i)
    coord_size.append(combined)
    
print(split)
print(coord_size)

matrix = np.zeros((20, 20))

for i in coord_size:
    coord = i[0]
    size  = i[1]
    x, y = coord
    width, height = size
    for coord_y in range(y, height+y):
        for coord_x in range(x, width+x):
            matrix[coord_y, coord_x] +=1

overlap = np.count_nonzero(matrix >1)

print(overlap)

print(matrix)




['#1 @ 1,3: 4x4\n', '#2 @ 3,1: 4x4\n', '#3 @ 5,5: 2x2 \n']
[['#1', '@', '1,3:', '4x4'], ['#2', '@', '3,1:', '4x4'], ['#3', '@', '5,5:', '2x2']]
[([1, 3], [4, 4]), ([3, 1], [4, 4]), ([5, 5], [2, 2])]
4
range(5, 7)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [17]:
import numpy as np

with open('input', 'r') as test:
    test = test.readlines()
#print(test)

split = []
coord_size = []
for i in test:
    split_i = i.split()
    start_coord = split_i[2]
    size = split_i[3]
    start_coord_ = start_coord[:-1]
    start_coord_split = list(map(int, start_coord_.split(',')))
    size_split = list(map(int, size.split('x')))
    combined = (start_coord_split, size_split)
    split.append(split_i)
    coord_size.append(combined)
    
#print(split)
#print(coord_size)

matrix = np.zeros((2000, 2000))

for i in coord_size:
    coord = i[0]
    size  = i[1]
    x, y = coord
    width, height = size
    for coord_y in range(y, height+y):
        for coord_x in range(x, width+x):
            matrix[coord_y, coord_x] +=1

overlap = np.count_nonzero(matrix >1)

print(overlap)

print(matrix)




103806
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
